services:
  - type: web
    name: draft-b
    env: python
    buildCommand: |
      python3 -m venv venv
      . venv/bin/activate
      pip install -r requirements.txt
    startCommand: |
      . venv/bin/activate
      gunicorn --worker-class gevent -w 4 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: 0
      - key: GUNICORN_WORKERS
        value: 4
      - key: GUNICORN_WORKER_CLASS
        value: gevent
      - key: SECRET_KEY
        generateValue: true
