services:
  - type: web
    name: draft-b
    env: python
    buildCommand: |
      python3 -m venv venv
      . venv/bin/activate
      pip install -r requirements.txt
    startCommand: |
      . venv/bin/activate
      gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT 'app:app'
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: FLASK_ENV
        value: production
      - key: WEB_CONCURRENCY
        value: 1

databases:
  - name: draft-database
    region: frankfurt
    ipAllowList: []
    plan: free
